[tool.bumpversion]
current_version = "0.2.23"
commit = true
message = "Bump version: {current_version} → {new_version}"
commit_args = "--cleanup=verbatim"
tag = true
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "build/package/Dockerfile"
search = "LABEL version={current_version}"
replace = "LABEL version={new_version}"
